Fix executeShopifyGraphQL import path
- Change import from ./utils/shopifyApi.js to ./utils/tokenResolver.js
- executeShopifyGraphQL function is defined in tokenResolver.js
- Should fix GraphQL queries in storeMetadata resolver
- Fixes TypeError: executeShopifyGraphQL is not a function